### ISSUE TITLE
How does async-extras deprecate async-manager?

### ISSUE THREAD

**Issue by joe9** [jfischoff/async-extras#2]
Hello,

Thanks for sharing async-extras.

I have a bunch of async threads. I am looking for a library that can help me manage those threads. Async-manager seems geared for this task.

In the async-manager Readme, it is mentioned that async-extras deprecate the functionality of async-manager. I could not find any sample code or example showing how to use async-extras as a thread manager.

Any kind comments, please?

Thanks

**Comment by jfischoff** [comment]
I wrote the manager because I wanted to be able pass the Async to the "self" thread. This is possible with mfix/mdo and exposed in Async extras with `fixAsync` https://hackage.haskell.org/package/async-extras-0.1.2.0/docs/src/Control-Concurrent-Async-Extra.html#fixAsync

I think there is still a reason to have the manager ... but probably not in the current form. 

Also I would look at `threads` ThreadGroup: https://hackage.haskell.org/package/threads-0.5.1.4/docs/Control-Concurrent-Thread-Group.html

**Comment by joe9** [comment]
Thanks
